version: "3.7"

services:
  echo:
    image: golang:1.16.0-alpine3.13
    expose:
      - "9099"
    command: go run echo.go
    working_dir: /wstcp/example
    volumes:
      - ../:/wstcp

  autobahn:
    image: crossbario/autobahn-testsuite
    command: wstest --mode fuzzingclient --debug --spec /autobahn/config.json
    depends_on:
      - echo
    volumes:
      - ./autobahn:/autobahn
