version: "3.7"

services:
  example:
    image: golang:1.16.0-alpine3.13
    expose:
      - "9099"
    command: go run .
    working_dir: /wstcp/example
    volumes:
      - ../:/wstcp

  autobahn:
    image: crossbario/autobahn-testsuite
    command: wstest --mode fuzzingclient --debug --spec /autobahn/config.json
    depends_on:
      - example
    ports:
      - "9001:9001"
    volumes:
      - ./autobahn:/autobahn
